### ISSUE TITLE
how to convert mobilenet_v1.pkl to tensorflow pb file?

### ISSUE THREAD

**Issue by samsun639** [MG2033/MobileNet#2]
Could you guide how to convert mobilenet_v1.pkl to tensorflow pb file?

Thanks!

**Comment by MG2033** [comment]
Just run the code and enable training. Before it finishes the first epoch, press CTRL+C to break. It will save model checkpoint automatically in the experiments directory.

**Comment by zhcv** [comment]
@MG2033 , Hey , Wｈａｔ  is the use of  `calculate_flops()``` in `utils.py`　, how to use it
