### ISSUE TITLE
I have a question during code review.

### ISSUE THREAD

**Issue by seongkyun** [MG2033/MobileNet#3]
Hello. I'm studying about parameter reduction and newbie in deep learning stuffs.

I have a question about data_loader.py

I've ran main.py with config.json that included originally, and it works well i think.

but during data loading, there is only jpeg images and loaded only images without any kinds of class information.

So my question is,

How it(code) calculates predicted accuracy without image's original class information?

I can not find any kinds of loading class information in data_loader.py

plz help me guyz :)

**Comment by goncalopalaio** [comment]
I just stumbled into this project but I may be able to answer

If you look closely at data_loader, it actually loads both the image and the original class information. Maybe you didn’t notice because it’s encoded as an integer.

> self.y_train = np.array([284, 264, 682, 2])

This number should map to your class name list.

**Comment by FB-wh** [comment]
Poor  readability
