### ISSUE TITLE
how can i convert other pre-train weights to pkl format?

### ISSUE THREAD

**Issue by zhen8838** [MG2033/MobileNet#5]
i want to use MobileNet_v1_0.25_224 weights,but i don't know how to convert ckpt to pkl format. can you help me? Thanks..

**Comment by moemen95** [comment]
Hello zhen
Load the checkpoint of the model in the code.
Then loop on tf.all_variables of tensorflow and run the session on every variable.
Then save all variables in a dict which contains the name of the tensor and its value.
Let me if you got me or not xD

**Comment by zhen8838** [comment]
Thanks a lot~
