### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by ohcurrent** [MG2033/MobileNet#7]
As I am not used to python, I need some help running the MobileNet. Please help :)

When I do 'python main.py config/test.json'
It prints out 
'main.py: error: unrecognized arguments: config/test.json
Add a config file using '--config file_name.json'

What do I have to do?

Thank you.

**Comment by jeffin07** [comment]
@ohcurrent i think it's an issue with python version.Can you try it with python3 
`python3 main.py --config config/test.json
`
it will probably resolve the issue
